### ISSUE TITLE
There already is vr for fabric

### ISSUE THREAD

**Issue by Sshmoob** [GiantLuigi4/FabriVR#1]
You don't have to work on this anymore if you don't want to, it already exists, and it works stand alone which means you don't need a pc. 
Link: https://github.com/QuestCraftPlusPlus/QuestCraft

**Comment by Sshmoob** [comment]
I posted this because your last commit is just
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by GiantLuigi4** [comment]
I haven’t worked on this in a long while, but uh I don’t have an oculus quest, I have an oculus rift, so that wouldn’t work for me

**Comment by GiantLuigi4** [comment]
There’s also minexraft or smth like that, but I don’t know where the link to the repo of that is
